version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
    schedule:
      interval: daily
    assignees:
      - "qraimbault"
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
    schedule:
      interval: daily
    assignees:
      - "qraimbault"
