name: CI
on: [push]
jobs:
  lintbuild:
    name: Lint & Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest
